FROM python:3.11

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8501:8501

CMD ["streamlit", "run", "/app/src/streamlit/main.py", "--server.port", "8501"]

